# Generated by Django 4.2.3 on 2023-12-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
    ]
