# Generated by Django 4.2.3 on 2023-12-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Todoapp", "0002_alter_task_options_remove_task_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
