# Generated by Django 4.0.6 on 2023-11-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Itapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='task',
            field=models.CharField(max_length=255),
        ),
    ]
