# Generated by Django 4.0.6 on 2023-11-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Itapp', '0003_rename_date_post_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='completed',
        ),
    ]
