# Generated by Django 4.2.3 on 2023-12-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Itapp", "0004_remove_post_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
